### ISSUE TITLE
feat: convert should confirm inputs and modify only if appropriate

### ISSUE THREAD

**Issue by SgtPooki** [ipld/js-blockcodec-to-ipld-format#1]
see https://github.com/ipfs/ipld-explorer-components/pull/356#discussion_r1113394569

**Comment by BigLep** [comment]
@SgtPooki : from IPLD triage (which has minimal maintainers right now) this isn't something that IPLD maintainers will take on.  If this is important/blocking for Ignite, we'll need Ignite to own it.  (Feel free to add to the Ignite project board.)

**Comment by BigLep** [comment]
Closing given comments before.  Feel free to reopen and take on @SgtPooki if needed.
